baseURL = 'https://hugo.linuxer.name/'
languageCode = 'ko-kr'
title = 'Linuxer Blog'
theme = 'PaperMod'

[params]
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowShareButtons = false
  ShowToc = true
  TocOpen = false
  displayFullLangName = true
  hideMeta = false
  hideMetaInList = false
  defaultTheme = "dark"
  disableThemeToggle = false

[params.homeInfoParams]
  Title = "Linuxer Blog"
  Content = "AWS, Linux, Kubernetes 기술 블로그"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Cloud-Linuxer"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 30

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 40

[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = true
  style = "dracula"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[outputs]
  home = ["HTML", "RSS", "JSON"]
