baseURL = 'https://www.linuxer.name/'
languageCode = 'ko-kr'
title = 'Linuxer Blog'
theme = 'PaperMod'

[params]
  ShowCodeCopyButtons = true
  diagram = false
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowShareButtons = false
  ShowToc = true
  TocOpen = false
  displayFullLangName = true
  hideMeta = false
  hideMetaInList = false
  defaultTheme = "dark"
  disableThemeToggle = true
  summaryLength = 70
  ShowSearch = true

[params.homeInfoParams]
  Title = ""
  Content = "리눅서의 기술 블로그"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Cloud-Linuxer"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/taehwan-jeong-274846190/"

[[params.socialIcons]]
  name = "other"
  title = "KakaoTalk"
  url = "https://open.kakao.com/o/gMCqYXxb"

[[params.socialIcons]]
  name = "email"
  url = "mailto:linuxer.name@gmail.com"

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 5

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 30

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 40

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
      [markup.goldmark.extensions.passthrough]
        enable = false
        [markup.goldmark.extensions.passthrough.delimiters]
          block = []
          inline = []
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    lineNumbersInTable = false
    style = "dracula"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = ["title", "permalink", "summary", "content", "tags", "categories"]
